language: ruby
rvm:
- 2.0.0
env:
- DB=postgresql
cache: bundler
script:
- bundle install
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database tumitfahrer_test' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: Ow7CHRkDOz7sE4KaCcMn8McKMgCOWwGyjDzw96qe+a7lH/caHxmYY6DIw7ntURdlfIXfFT9Bp0SAXSDdBQop2RuYoUfD2JcQ664d7dwRNoDd+nP9H5mfQKZErXCxnrGPa+zlI/0uyWCf1QCanOxVhNcfySIHg0yErKb/eq2AOHU=
  app:
    develop: tumitfahrer
  run:
    - "rake db:migrate"
notifications:
  email: false